### ISSUE TITLE
demultiplex unknown results

### ISSUE THREAD

**Issue by seven1112233** [jfjlaros/demultiplex#28] opened 2022-11-24 03:13 UTC
hi, I use demultiplex to separate my long reads file.  it is a useful tool. but there are some questions about tools usage. After demultiplex, I found some reads which are assigned to unknown file also exist in one of barcode_results_file, and I also found there are some reads repeatedly exist in unknown files I want to know why this happen? 
![1669259553467](https://user-images.githubusercontent.com/71070001/203685891-577f0675-7f0b-4576-b04e-bbf24ab123fe.png)
![1669260592907](https://user-images.githubusercontent.com/71070001/203687727-1df3fa44-dc4c-449b-9fc6-2a4c26d206bd.png)

**Comment by jfjlaros** [comment] 2022-11-24 12:56
Can you provide a minimal example?

- A snippet of the input files (one read should be enough).
- The barcodes file.
- The command line parameters used.

**Comment by seven1112233** [comment] 2022-11-24 13:05
1.code
demultiplex match \
-m 2 -f \
-p ${demultiplex}/ \

barcode fastq.gz


2. barcode
Cas9_SSP&nbsp; &nbsp; &nbsp; &nbsp; TTTCTGTTGGTGCTGATATTGCTTAGCTT
Cas9_VNP&nbsp; &nbsp; &nbsp; &nbsp; ACTTGCCTGTCGCTCTATCTTCTAGCTT
Cas9-fus_SSP&nbsp; &nbsp; TTTCTGTTGGTGCTGATATTGCTGGCTAC
Cas9-fus_VNP&nbsp; &nbsp; ACTTGCCTGTCGCTCTATCTTCGGCTAC



3.one of reads:
@a6d0dff0-0e9b-4f24-b35a-4845e87cf04a runid=dba5214c8a7cdca61f048e7506092585a8adb9ba sampleid=20221115_polII_Y732_met1-2_nuc_RNA read=12539 ch=325 start_time=2022-11-16T07:22:12Z barcode=barcode01
GGCTCAAGCTCGTTCAGTTCCATGTGGAGGGTAGGTGTTTAACCAGTCATAACCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCTTAGCTTCACACAATGCCTGACCAGTTTCATCTATAATGGGGATGCCACATAGTCCCACAGCCAGGAGCTGGGTGGTCAGTTTTGTCAGTGGTGACTCAGCATCTGGATAGCATATCCCTAAAGTGCAAGAATTGACACATTTGCATATGCATTTTTTATGGCACATGAATGTTGTGTTTATATACATATGCTTTTTTAACTAAAGAAGAAAAATAACCCTGCCCTTTGTACGCGATCCTTTTAACAAACTGTTTATTATTGTATCCAGGTAACAAACATGGTAAGTATGTTCTCTAAACTGAGTATTCTGTATTTTTAGCTGTGCTTGGCAGATTTTTTTTTTCTTTTTTGGCTAGCTTTGTGTTACCAATCTTGGCTTTGTAGAAAGATCCATTTTGGAAAGGAAACACTGCTAGCCACTCCCCCACACTCCTGAGCTTTGGTAAAGGAACCCCTGTAGCCTTATCCCCATAGCATGTGCCCCACAGCATGCTGCTTGGCTGCTCCCCTACCCGTCTGCTGCTTTGTGAGCTGCCCCTCCTCGGATGTCTGCCAGGGTTCCTGGGCCTGGAATGACCTCAGCAGGGGCCTGGCACTGGCCCAACGACAGCAGGCACCCAAATAGTGCTCTCTTCGATCTGTGGATGGCCCTACCCCCTGCTGGTGACCTTCATGAAAGTCAGGTCACCCAAGCTAGAAGATAGAGCGACAGGCAAGTCACAAAGACACCGACAACTTTCTTGTCA
+

***@***.***@&gt;=9957,+3:A?=<:B?F73:;761-042876;;33328568656568<=@=9:988;&gt;6&gt;;<9=7=89?@***@***.***<;8)A@<2&gt;=<3:2=<<&gt;<;:C7&gt;<?C?=ED=78&gt;?;D&gt;=::::987<78=:<:748<9&gt;8;<@***@***.***/:5=&gt;=&gt;<575==8)482-./11.3@@@***@***.***?8A;?@@=<<9:<<&gt;=<5557433*/78*+'@@=@***@***.******@***.***:==@=?A?5&amp;-'%6594''567<=<:;;7=B&gt;@?=:2567&gt;@?<;95,/045&gt;;=9&gt;==89;<&gt;9:;84,,//*%'2221(7<;;&gt;<?@***@***.******@***.***&gt;@&gt;%8.*)1.01/%($$$$&amp;047&gt;@?<@?CA@<A&gt;&gt;<&gt;@?AE&gt;=8;&gt;AAA=<:?A?=71-0546@&gt;A?8<://2?;?<:;9=<8;78C=;765348<:39768896;;&gt;67AC&gt;<&gt;?EBAC@;89701=<87:<2<767:=67892,=A?<./523,*),448@@***@***.******@***.***&gt;&gt;7;</,/$


thank you for your reply! if you need more information, please tell me!


Dinasour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jfjlaros/demultiplex"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 晚上8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jfjlaros/demultiplex] demultiplex unknown results (Issue #28)





 
Can you provide a minimal example?
  
A snippet of the input files (one read should be enough).
 
The barcodes file.
 
The command line parameters used.

**Comment by jfjlaros** [comment] 2022-11-24 15:53
I can not reproduce the issue with the provided read. There is only one output file (the one for `Cas9_SSP`).

**Comment by jfjlaros** [comment] 2022-12-07 20:20
I am closing this issue for now since I can not reproduce the problem. Feel free to reopen it when you have an example.

**Closed by jfjlaros** 2022-12-07 20:20 UTC
Labels: waiting for feedback
